[package]
name = "stos-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
ffmpeg-next = "6.0.0"
image = "0.24.6"
lexopt = "0.3.0"
log = "0.4.19"
pretty_env_logger = "0.5.0"
