[package]
name = "stos"
version = "0.1.0"
authors = ["Hyxogen"]
edition = "2021"
license = "MIT"
repository = "https://github.com/Hyxogen/stos"
keywords = ["anki", "subs2srs", "srs"]
categories = ["command-line-utilities", "multimedia"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/extract"]

[dependencies]

[dev-dependencies]
