[package]
name = "stos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.1", features = ["derive"] }
clap-verbosity-flag = "2.0.1"
ffmpeg-next = "6.0.0"
glob = "0.3.1"
log = "0.4.18"
pretty_env_logger = "0.5.0"

[dev-dependencies]
assert_cmd = "2.0.11"
predicates = "3.0.3"
